"""empty message

Revision ID: 2f6f38df8ad
Revises: 7310aac914
Create Date: 2015-05-11 10:05:03.543133

"""

# revision identifiers, used by Alembic.
revision = '2f6f38df8ad'
down_revision = '7310aac914'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('error', sa.Column('false_positive', sa.Boolean()))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('error', 'false_positive')
    ### end Alembic commands ###
