"""empty message

Revision ID: 4805455a3ce
Revises: 1516781f333
Create Date: 2015-09-14 14:29:50.489566

"""

# revision identifiers, used by Alembic.
revision = '4805455a3ce'
down_revision = '1516781f333'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comment_version',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('text', sa.Text(), autoincrement=False, nullable=True),
    sa.Column('error_id', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('external_id', sa.String(length=120), autoincrement=False, nullable=True),
    sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('end_transaction_id', sa.BigInteger(), nullable=True),
    sa.Column('operation_type', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'transaction_id')
    )
    op.create_index(op.f('ix_comment_version_end_transaction_id'), 'comment_version', ['end_transaction_id'], unique=False)
    op.create_index(op.f('ix_comment_version_operation_type'), 'comment_version', ['operation_type'], unique=False)
    op.create_index(op.f('ix_comment_version_transaction_id'), 'comment_version', ['transaction_id'], unique=False)
    op.create_table('error_version',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('highlight', sa.Text(), autoincrement=False, nullable=True),
    sa.Column('kind', sa.String(length=120), autoincrement=False, nullable=True),
    sa.Column('subkind', sa.String(length=120), autoincrement=False, nullable=True),
    sa.Column('severity', sa.String(length=120), autoincrement=False, nullable=True),
    sa.Column('false_positive', sa.Boolean(), autoincrement=False, nullable=True),
    sa.Column('story_id', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('project_id', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('end_transaction_id', sa.BigInteger(), nullable=True),
    sa.Column('operation_type', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'transaction_id')
    )
    op.create_index(op.f('ix_error_version_end_transaction_id'), 'error_version', ['end_transaction_id'], unique=False)
    op.create_index(op.f('ix_error_version_kind'), 'error_version', ['kind'], unique=False)
    op.create_index(op.f('ix_error_version_operation_type'), 'error_version', ['operation_type'], unique=False)
    op.create_index(op.f('ix_error_version_transaction_id'), 'error_version', ['transaction_id'], unique=False)
    op.create_table('integration_version',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('kind', sa.String(length=120), autoincrement=False, nullable=True),
    sa.Column('api_token', sa.String(length=250), autoincrement=False, nullable=True),
    sa.Column('project_id', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('integration_project_id', sa.String(length=250), autoincrement=False, nullable=True),
    sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('end_transaction_id', sa.BigInteger(), nullable=True),
    sa.Column('operation_type', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'transaction_id')
    )
    op.create_index(op.f('ix_integration_version_end_transaction_id'), 'integration_version', ['end_transaction_id'], unique=False)
    op.create_index(op.f('ix_integration_version_operation_type'), 'integration_version', ['operation_type'], unique=False)
    op.create_index(op.f('ix_integration_version_transaction_id'), 'integration_version', ['transaction_id'], unique=False)
    op.create_table('project_version',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('name', sa.String(length=120), autoincrement=False, nullable=True),
    sa.Column('format', sa.Text(), autoincrement=False, nullable=True),
    sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('end_transaction_id', sa.BigInteger(), nullable=True),
    sa.Column('operation_type', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'transaction_id')
    )
    op.create_index(op.f('ix_project_version_end_transaction_id'), 'project_version', ['end_transaction_id'], unique=False)
    op.create_index(op.f('ix_project_version_name'), 'project_version', ['name'], unique=False)
    op.create_index(op.f('ix_project_version_operation_type'), 'project_version', ['operation_type'], unique=False)
    op.create_index(op.f('ix_project_version_transaction_id'), 'project_version', ['transaction_id'], unique=False)
    op.create_table('story_version',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('external_id', sa.String(length=120), autoincrement=False, nullable=True),
    sa.Column('text', sa.Text(), autoincrement=False, nullable=True),
    sa.Column('role', sa.Text(), autoincrement=False, nullable=True),
    sa.Column('means', sa.Text(), autoincrement=False, nullable=True),
    sa.Column('ends', sa.Text(), autoincrement=False, nullable=True),
    sa.Column('project_id', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('end_transaction_id', sa.BigInteger(), nullable=True),
    sa.Column('operation_type', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'transaction_id')
    )
    op.create_index(op.f('ix_story_version_end_transaction_id'), 'story_version', ['end_transaction_id'], unique=False)
    op.create_index(op.f('ix_story_version_operation_type'), 'story_version', ['operation_type'], unique=False)
    op.create_index(op.f('ix_story_version_transaction_id'), 'story_version', ['transaction_id'], unique=False)
    op.create_table('transaction',
    sa.Column('issued_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('remote_addr', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transaction')
    op.drop_index(op.f('ix_story_version_transaction_id'), table_name='story_version')
    op.drop_index(op.f('ix_story_version_operation_type'), table_name='story_version')
    op.drop_index(op.f('ix_story_version_end_transaction_id'), table_name='story_version')
    op.drop_table('story_version')
    op.drop_index(op.f('ix_project_version_transaction_id'), table_name='project_version')
    op.drop_index(op.f('ix_project_version_operation_type'), table_name='project_version')
    op.drop_index(op.f('ix_project_version_name'), table_name='project_version')
    op.drop_index(op.f('ix_project_version_end_transaction_id'), table_name='project_version')
    op.drop_table('project_version')
    op.drop_index(op.f('ix_integration_version_transaction_id'), table_name='integration_version')
    op.drop_index(op.f('ix_integration_version_operation_type'), table_name='integration_version')
    op.drop_index(op.f('ix_integration_version_end_transaction_id'), table_name='integration_version')
    op.drop_table('integration_version')
    op.drop_index(op.f('ix_error_version_transaction_id'), table_name='error_version')
    op.drop_index(op.f('ix_error_version_operation_type'), table_name='error_version')
    op.drop_index(op.f('ix_error_version_kind'), table_name='error_version')
    op.drop_index(op.f('ix_error_version_end_transaction_id'), table_name='error_version')
    op.drop_table('error_version')
    op.drop_index(op.f('ix_comment_version_transaction_id'), table_name='comment_version')
    op.drop_index(op.f('ix_comment_version_operation_type'), table_name='comment_version')
    op.drop_index(op.f('ix_comment_version_end_transaction_id'), table_name='comment_version')
    op.drop_table('comment_version')
    ### end Alembic commands ###
