"""empty message

Revision ID: 5199ac2b07
Revises: 59a63640eae
Create Date: 2015-09-09 10:23:42.502178

"""

# revision identifiers, used by Alembic.
revision = '5199ac2b07'
down_revision = '59a63640eae'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('integration', sa.Column('project_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'integration', 'project', ['project_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'integration', type_='foreignkey')
    op.drop_column('integration', 'project_id')
    ### end Alembic commands ###
