"""empty message

Revision ID: 56580e83683
Revises: 53ee445aa95
Create Date: 2015-09-09 17:31:28.129161

"""

# revision identifiers, used by Alembic.
revision = '56580e83683'
down_revision = '53ee445aa95'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('external_id', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comment')
    ### end Alembic commands ###
