"""empty message

Revision ID: 59a63640eae
Revises: 25253238bc5
Create Date: 2015-09-09 10:21:42.447852

"""

# revision identifiers, used by Alembic.
revision = '59a63640eae'
down_revision = '25253238bc5'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('integration',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=120), nullable=False),
    sa.Column('api_token', sa.String(length=250), nullable=False),
    sa.Column('integration_project_id', sa.String(length=250), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('users')
    op.drop_table('schema_migrations')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('schema_migrations',
    sa.Column('version', sa.VARCHAR(), autoincrement=False, nullable=False)
    )
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('email', sa.VARCHAR(), server_default=sa.text("''::character varying"), autoincrement=False, nullable=False),
    sa.Column('encrypted_password', sa.VARCHAR(), server_default=sa.text("''::character varying"), autoincrement=False, nullable=False),
    sa.Column('reset_password_token', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('reset_password_sent_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('remember_created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('sign_in_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('current_sign_in_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('last_sign_in_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('current_sign_in_ip', postgresql.INET(), autoincrement=False, nullable=True),
    sa.Column('last_sign_in_ip', postgresql.INET(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='users_pkey')
    )
    op.drop_table('integration')
    ### end Alembic commands ###
